## YAML Template.
application:
    planner-assistant-2020
runtime: java
api_version: 1
threadsafe: true

env: flex
runtime_config:
    jdk: openjdk14
handlers:
- url: /.*
  script: PlannerServerApplication.app

