## YAML Template.
application:
    spring-gc
runtime: java
api_version: 1
threadsafe: true

env: flex
runtime_config:
    jdk: openjdk8
handlers:
- url: /.*
  script: PlannerServerApplication.app
---
